import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/layout/root";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Punjab Aviation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
