import { alpha } from "@mui/material";

export const styles = {
  tabsWrapper: () => ({
    background: "transparent",
    borderRadius: "8px",
    display: "inline-block",
    padding: "4px",
    height: "4rem",
    marginBottom: "8px",
    "& ._indicator": {
      display: "none",
    },
    "& ._root, ": { minHeight: "unset", maxWidth: "100%" },
    "& .tab_root": {
      height: "40px",
      marginLeft: "1rem !important",
      zIndex: 1,
      padding: "4px 20px",
      minHeight: "unset",
      textTransform: "capitalize",
      color: "#64748B",
      fontSize: "16px",
      fontWeight: 500,
      lineHeight: "24px",
      background: "#fff",
      boxShadow: `0px 4px 8px -2px rgba(16, 24, 40, 0.18)`,
      backdropFilter: "blur(12px)",
      borderRadius: "6px",
      "&._selected": {
        color: "#F8FAFC",
        height: "40px",
        background: "#2278C8",
        boxShadow: `0px 4px 8px -2px rgba(16, 24, 40, 0.18)`,
        backdropFilter: "blur(12px)",
        borderRadius: "6px",
        fontSize: "16px",
        fontWeight: 500,
        padding: "4px 20px",
        minHeight: "unset",
        textTransform: "capitalize",
        marginLeft: "1rem !important",
        zIndex: 1,
      },
    },
  }),
};
